apiVersion: v1
kind: Service
metadata:
  name: upscale
  namespace: upscale
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /health
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTPS
spec:
  ports:
    - port: 443
      targetPort: 5000
      protocol: TCP
      name: https
  selector:
    app: upscale
  type: LoadBalancer
  loadBalancerSourceRanges:
  # - x.x.x.x/32